-- 사진 컬렉션 공개 공유(2026-08-30, Phase 2)
-- 공개 사진 컬렉션이 "남의 카드에도 사진까지" 보이게 하려면 public_collections에 photos 배열이 필요하다.
-- (기존 공개 테이블은 영상 items만 담아서 사진 컬렉션은 남에게 빈 채로 보였음.)
-- 이 SQL을 Supabase SQL Editor에서 한 번 실행하면 끝. 앱은 photos 컬럼이 없어도 폴백하도록 돼 있어
-- (실행 전에도 영상 공개는 안 깨짐), 실행 후부터 공개 사진 컬렉션이 정상 동작한다.

-- 1) public_collections에 사진 배열 컬럼 추가 (jsonb — [{ "u": "url" }, ...])
alter table public.public_collections
  add column if not exists photos jsonb;

-- 2) 공개 사진 컬렉션 신고(부적절 콘텐츠 takedown 경로 — 법적 장치 #5/#6과 세트)
create table if not exists public.collection_reports (
  id           bigint generated by default as identity primary key,
  collection_id text        not null,
  reporter_id  uuid        references auth.users(id) on delete set null,
  reason       text,
  created_at   timestamptz not null default now()
);

alter table public.collection_reports enable row level security;

-- 누구나(익명 포함) 신고를 넣을 수 있게 — 신고는 열려 있어야 한다.
drop policy if exists collection_reports_insert on public.collection_reports;
create policy collection_reports_insert
  on public.collection_reports for insert
  to anon, authenticated
  with check (true);

-- 조회/삭제는 서버(서비스 롤)·관리자 콘솔에서만. 일반 클라이언트엔 select 정책을 열지 않는다
-- (신고 목록이 아무에게나 보이면 안 됨). 관리자 검수는 Supabase 대시보드에서 본다.

create index if not exists idx_collection_reports_collection on public.collection_reports(collection_id);
