-- 수동 태깅 편집 이력(2026-08-31) — "학습하는 태깅 파이프라인"의 토대.
--
-- 배경: 지금 관리자가 편집 모달에서 태그를 고치면 그 행에 tags_manual=true 플래그만 남고,
-- **무엇을 무엇으로 고쳤는지는 어디에도 안 남는다.** 그래서 "자동 태깅이 뭘 틀렸는지"라는
-- 가장 값진 신호가 편집할 때마다 그대로 버려지고 있었다(사용자 요청: "내 수동 태깅 편집 결과를
-- 보고 학습해서 로직을 계속 고도화하는 시스템"). 이 테이블이 그 원료를 쌓는다.
--
-- 쓰임새 3가지:
--   ① 회귀 골든셋 — before/after가 쌓이면 "현재 매처를 다시 돌렸을 때 사람 판단과 얼마나 일치하나"를
--      숫자로 잴 수 있다(tools/m2_harness.js 확장).
--   ② 규칙 후보 자동 제안 — 같은 이름/같은 패턴이 반복해서 제거되면(예: '한'이 30번 지워짐)
--      흔한단어 보호(name_match_whitelist) 후보로 자동 승격 제안.
--   ③ 사고 추적 — 대량 스윕이 사람 판단을 덮었는지 사후 확인(admin_bulk_snapshots는 되돌리기용
--      1회분만 보관하고 지워지므로, 장기 이력은 여기에만 남는다).
--
-- Supabase SQL Editor에서 한 번 실행. (앱은 이 테이블이 없으면 조용히 건너뛰도록 방어돼 있어
-- 실행 전에도 안 깨진다 — tag_review_queue와 같은 패턴.)

create table if not exists public.tag_edit_log (
  id         bigint generated by default as identity primary key,
  video_id   text        not null,
  title      text,        -- 편집 시점의 제목(행이 나중에 바뀌어도 로그만으로 재현 가능하게 비정규화)
  before     jsonb        not null default '{}'::jsonb,  -- 편집 전 태그 상태
  after      jsonb        not null default '{}'::jsonb,  -- 편집 후 태그 상태
  changed    text[],      -- 실제로 값이 달라진 필드명만(예: {members,group_ko})
  source     text,        -- 'modal_single' | 'modal_bulk' | 'vm_bulk_flag' | 'vm_flag' | 'card_flag'
  editor     text,        -- 편집한 사람(로그인 이메일)
  created_at timestamptz not null default now()
);

-- 최근 이력 조회(대시보드)와 "이 영상 편집 이력" 조회 둘 다 자주 쓴다.
create index if not exists idx_tag_edit_log_recent on public.tag_edit_log (created_at desc);
create index if not exists idx_tag_edit_log_video  on public.tag_edit_log (video_id, created_at desc);
-- 규칙 후보 집계는 "특정 필드가 바뀐 이력"만 훑는다 — 배열 포함 검색용.
create index if not exists idx_tag_edit_log_changed on public.tag_edit_log using gin (changed);

alter table public.tag_edit_log enable row level security;

-- 관리자만 읽고 쓴다 — 클라이언트 _isAdmin()과 동일하게 로그인 이메일로 판별.
-- (관리자 이메일이 바뀌면 아래 주소를 같이 바꿔 실행할 것.)
drop policy if exists tag_edit_log_admin_all on public.tag_edit_log;
create policy tag_edit_log_admin_all
  on public.tag_edit_log for all
  to authenticated
  using ((auth.jwt() ->> 'email') = 'before0hwa@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'before0hwa@gmail.com');
