-- 태깅 검수 대기열(2026-08-30) — 사람이 판단해야 하는 "애매한" 케이스를 화면에 쌓는다.
-- 배경: 지금은 스윕이 판단 못 한 행(예: 멤버 태그가 전부 빠져 무관인지 정상인지 애매)을 브라우저
-- 콘솔(console.log)에만 남겨서, 검수 센터에 들어가도 실제로 처리할 목록이 없었다(그래서 손이 안 감).
-- 이 테이블에 "고신뢰 애매" 케이스만 적재하고, 어드민 홈 카운트 → 검수 대기 목록 → 편집 → 해결로 잇는다.
-- Supabase SQL Editor에서 한 번 실행. (앱은 이 테이블이 없으면 조용히 건너뛰도록 방어돼 있어 실행 전에도 안 깨짐.)

create table if not exists public.tag_review_queue (
  id          bigint generated by default as identity primary key,
  video_id    text        not null,
  reason      text,        -- 왜 대기인지(예: 'members_wiped' = 재검증에서 멤버 태그가 전부 빠짐)
  source      text,        -- 어느 경로에서 넣었는지(예: 'members_reverify','scoped_reverify')
  detail      jsonb,       -- 부가정보(제거된 멤버 등)
  created_at  timestamptz not null default now(),
  resolved_at timestamptz,
  unique (video_id, reason)  -- 같은 영상·같은 이유 중복 방지(dedup) — 재적재는 조용히 무시/갱신
);

create index if not exists idx_tag_review_queue_open
  on public.tag_review_queue (created_at) where resolved_at is null;

alter table public.tag_review_queue enable row level security;

-- 관리자만 읽고 쓴다 — 클라이언트 _isAdmin()과 동일하게 로그인 이메일로 판별(ADMIN_EMAIL).
-- (관리자 이메일이 바뀌면 아래 두 곳의 주소를 같이 바꿔 실행할 것.)
drop policy if exists tag_review_queue_admin_all on public.tag_review_queue;
create policy tag_review_queue_admin_all
  on public.tag_review_queue for all
  to authenticated
  using ((auth.jwt() ->> 'email') = 'before0hwa@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'before0hwa@gmail.com');
