-- 되돌리기: 드림캐쳐 유아유(UAU) 태그 복구 (2026-09-28)
-- fix_rank_findings_2026-09-28.sql이 "동명 신인 그룹"이라는 잘못된 추측으로 유아유(2025 데뷔 드림캐쳐 유닛) 영상의
-- 멤버·게스트 태그를 지우고 보류 처리했다. 그 SQL이 건드린 행만 정확히 원상 복구한다.
BEGIN;
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = 'yrLQNSjTujg' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'yrLQNSjTujg' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = 'dAFMFwzPbgA' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'dAFMFwzPbgA' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = 'dAFMFwzPbgA' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'dAFMFwzPbgA' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = 'Y3I0KqNfS84' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'Y3I0KqNfS84' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = 'Y3I0KqNfS84' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'Y3I0KqNfS84' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = 'kWaOxLagCDg' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'kWaOxLagCDg' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = 'kWaOxLagCDg' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'kWaOxLagCDg' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = 'UvmYRccqed4' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'UvmYRccqed4' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = 'UvmYRccqed4' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'UvmYRccqed4' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = '2FLTl0k1Ffg' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = '2FLTl0k1Ffg' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = '2FLTl0k1Ffg' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = '2FLTl0k1Ffg' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = '1R7sZudtl1U' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = '1R7sZudtl1U' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '지유') WHERE id = 'hs2ca2qMzh0' AND NOT (members @> ARRAY['지유']);
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'hs2ca2qMzh0' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = 'hs2ca2qMzh0' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'hs2ca2qMzh0' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'N7iMCLDw5IA' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'N7iMCLDw5IA' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '수아') WHERE id = 'EJiSxIfibBg' AND NOT (members @> ARRAY['수아']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'EJiSxIfibBg' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = '52pemI-0biA' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = '52pemI-0biA' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET members = array_append(members, '유현') WHERE id = 'UFgSHRMM6Qc' AND NOT (members @> ARRAY['유현']);
UPDATE yt_channel_videos SET content_flag = NULL, flag_source = NULL, flagged_at = NULL, needs_review = false WHERE id = 'UFgSHRMM6Qc' AND content_flag = '보류' AND flag_source = 'auto';
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = 'uDkpNufPK0M' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = 'gdI01yughGk' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = '9UMj22MW5iQ' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = 'VzMzPq82Vg4' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = 'LlvdUqph13g' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = '0s4k3K6cn2s' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = '2-PQYMrGVtY' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = '4TzdRgSpoJw' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '지유(드림캐쳐)') WHERE id = 'Z6NXyGed6nQ' AND NOT (with_members @> ARRAY['지유(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = 'uDkpNufPK0M' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = 'gdI01yughGk' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = '9UMj22MW5iQ' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = 'VzMzPq82Vg4' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = 'LlvdUqph13g' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = '0s4k3K6cn2s' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = '2-PQYMrGVtY' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = '4TzdRgSpoJw' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '수아(드림캐쳐)') WHERE id = 'Z6NXyGed6nQ' AND NOT (with_members @> ARRAY['수아(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = 'uDkpNufPK0M' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = 'gdI01yughGk' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = 'VzMzPq82Vg4' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = 'LlvdUqph13g' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = '0s4k3K6cn2s' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = '2-PQYMrGVtY' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = '4TzdRgSpoJw' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
UPDATE yt_channel_videos SET with_members = array_append(with_members, '유현(드림캐쳐)') WHERE id = 'Z6NXyGed6nQ' AND NOT (with_members @> ARRAY['유현(드림캐쳐)']);
COMMIT;
